### ISSUE TITLE
W/MIUIScout App(13273): Event:APP_SCOUT_WARNING Thread:main backtrace on REDMI 9 PRO

### ISSUE THREAD

**Issue by madmouse17** [ufukhawk/safe_device#36]
![image](https://github.com/ufukhawk/safe_device/assets/33163281/80ef094f-8c80-42e2-a589-4578a6344297)

<details><summary>Details</summary>

```
W/MIUIScout App(13273):     at com.wongpiwat.trust_location.LocationAssistant$8.onResult(LocationAssistant.java:730)
W/MIUIScout App(13273):     at com.wongpiwat.trust_location.LocationAssistant$8.onResult(LocationAssistant.java:722)
W/MIUIScout App(13273):     at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage(com.google.android.gms:play-services-base@@18.1.0:6)
W/MIUIScout App(13273):     at android.os.Handler.dispatchMessage(Handler.java:106)
W/MIUIScout App(13273):     at android.os.Looper.loopOnce(Looper.java:210)
W/MIUIScout App(13273):     at android.os.Looper.loop(Looper.java:299)
W/MIUIScout App(13273):     at android.app.ActivityThread.main(ActivityThread.java:8319)
W/MIUIScout App(13273):     at java.lang.reflect.Method.invoke(Native Method)
W/MIUIScout App(13273):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
W/MIUIScout App(13273):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
I/libc    (13273): Requested dump for tid 13273 (.laraseksy_bloc)
W/MIUIScout App(13273): Enter APP_SCOUT_HANG state
W/MIUIScout App(13273):  (Current message: duration=5276ms seq=57 h=com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler w=1)
W/MIUIScout App(13273): Event:APP_SCOUT_HANG Thread:main backtrace:
W/MIUIScout App(13273):     at jdk.internal.misc.Unsafe.park(Native Method)
W/MIUIScout App(13273):     at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
W/MIUIScout App(13273):     at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
W/MIUIScout App(13273):     at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
W/MIUIScout App(13273):     at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
W/MIUIScout App(13273):     at com.google.android.gms.internal.location.zzau.getLastLocation(com.google.android.gms:play-services-location@@21.0.1:12)
W/MIUIScout App(13273):     at com.wongpiwat.trust_location.LocationAssistant.checkInitialLocation(LocationAssistant.java:494)
W/MIUIScout App(13273):     at com.wongpiwat.trust_location.LocationAssistant.access$600(LocationAssistant.java:57)
W/MIUIScout App(13273):     at com.wongpiwat.trust_location.LocationAssistant$8.onResult(LocationAssistant.java:730)
W/MIUIScout App(13273):     at com.wongpiwat.trust_location.LocationAssistant$8.onResult(LocationAssistant.java:722)
W/MIUIScout App(13273):     at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage(com.google.android.gms:play-services-base@@18.1.0:6)
W/MIUIScout App(13273):     at android.os.Handler.dispatchMessage(Handler.java:106)
W/MIUIScout App(13273):     at android.os.Looper.loopOnce(Looper.java:210)
W/MIUIScout App(13273):     at android.os.Looper.loop(Looper.java:299)
W/MIUIScout App(13273):     at android.app.ActivityThread.main(ActivityThread.java:8319)
W/MIUIScout App(13273):     at java.lang.reflect.Method.invoke(Native Method)
W/MIUIScout App(13273):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
W/MIUIScout App(13273):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

```
</details>

**Comment by ufukhawk** [comment]
safe_device: ^1.1.5

**Comment by HeronKyaw** [comment]
Hey @ufukhawk, it's still happening in 1.1.15 and 1.1.16. I've faced it on Redmi Note 11 pro 5g. I just hung and "The app is not responding" just shows up quite frequently. Even I exit the app.
