### ISSUE TITLE
 ANR triggered by main thread waiting for too long

### ISSUE THREAD

**Issue by TheManuz** [ufukhawk/safe_device#37]
I've got 49 ANRs on 21 users caused by `trust_location` package (logged on Firebase Crashlytics), which is a `safe_device` direct dependency.

It's worth noting that I'm not even using APIs that might call `trust_location`, since I don't call `canMockLocation` and `isSafeDevice`, I'm only using `isJailBroken` and `isRealDevice`.

This is the stacktrace:

```
main (timed waiting):tid=1 systid=8469 
       at sun.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1090)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1390)
       at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
       at com.google.android.gms.internal.location.zzau.getLastLocation()
       at com.wongpiwat.trust_location.LocationAssistant.checkInitialLocation(LocationAssistant.java)
       at com.wongpiwat.trust_location.LocationAssistant.access$600(LocationAssistant.java)
       at com.wongpiwat.trust_location.LocationAssistant$8.onResult(LocationAssistant.java)
       at com.wongpiwat.trust_location.LocationAssistant$8.onResult(LocationAssistant.java)
       at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage()
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8292)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

I know that's not your direct responsibility, but having several ANRs is concerning.

Is there something that can be done?

**Comment by MrLongg71** [comment]
I have the same problem, how to fix it?

**Comment by somarkn99** [comment]
In your code, you mentioned that you're not using the canMockLocation and isSafeDevice methods. Since ANRs are occurring in the trust_location package, try reducing the number of calls to these unused methods. You might be able to remove or optimize them.

**Comment by TheManuz** [comment]
@ufukhawk: could you consider removing `trust_location` package?

At the end of the day, if a user needs it, it can add `trust_location` itself and use it.

In this way, your package would only handle the root/jailbreak logic, and would not have other dependencies.

Just a random thought!

**Comment by YonatanSegura97** [comment]
Any workaround?

**Comment by TheManuz** [comment]
Right now, the only workaround is to use a fork.

I browsed many, and I found that this one fit my needs: https://github.com/ILazutin/safe_device

**Comment by kkjk1176** [comment]
@TheManuz Thank you so much. You saved my time.

**Comment by ufukhawk** [comment]
safe_device: ^1.1.5
