### ISSUE TITLE
not respond when the app is started

### ISSUE THREAD

**Issue by phanil** [ufukhawk/safe_device#53]
When used with geolocator, the UI will not respond when the app is started.

**Comment by rpekarek-tc** [comment]
I think we may be experiencing this issue as well. It doesn't happen on iOS, but causes issues for a select few android devices. It is consistently happening for the Pixel6a running Android version 14

**Comment by sadaqatdev** [comment]
This issue occur on Techno Devices

**Comment by sadaqatdev** [comment]
Use less Until run on all devices

**Comment by bagus-repository** [comment]
same issue

**Comment by sadaqatdev** [comment]
When it to be fix ?

**Comment by MelissaMashiro** [comment]
This is happening to me as well ... Please solve this issue

**Comment by ufukhawk** [comment]
@phanil can you give more details?

**Comment by MelissaMashiro** [comment]
@ufukhawk When using `safe_device` package along with `geolocator` package. The App installs correctly, but at the moment of building the UI, it gets stuck and then the console shows this message: " The application may be doing too much work on its main thread." After that, the app die. 
This doesnt happen on IOS devices.

**Comment by ufukhawk** [comment]
hmm, i will check this.

**Comment by MelissaMashiro** [comment]
Thanks, let me know if you need more evidence

**Comment by daffigusti** [comment]
same issue here.

**Comment by ufukhawk** [comment]
How did you understand that the problem was with the **safe_device** ? Can I get an error message?

**Comment by ufukhawk** [comment]
try again : safe_device: ^1.1.9

**Comment by YaseenSaif** [comment]
Any update

**Comment by mahesh87ta** [comment]
same issue, if we disable to location permission, the issue is not re producible and working smoothly. Any help on it?

**Comment by bharathiselvan** [comment]
I also face this issue. Any suggestions for resolving it?

**Comment by masgari0007** [comment]
I think the issue has to do with this bit of code inside the `MockLocation.LocationAssistant.acquireLocation` lines 456-466. I'm not even doing checks against location (just doing emulator checks) yet this code still runs on start up. Downgrading to `1.1.4` before this class is introduced fixes the issue though you will lose the other upgrades.

```java
        if (!updatesRequested) {
            requestLocationUpdates();
            // Check back in a few
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    acquireLocation();
                }
            }, 10000);
            return;
        }
```

**Comment by ammarayoubi** [comment]
I solved my problem using the following code:
final bool isMockLocation = (await Geolocator.getCurrentPosition()).isMocked;

**Comment by douglasfaria10** [comment]
In my case, remove safe_device works.

**Comment by corepuncher** [comment]
I am also getting this:

`I/Choreographer( 8160): Skipped 718 frames!  The application may be doing too much work on its main thread.
`
- Strangely, the first time it worked, but after restarting app, it hangs for along time. Maybe that is because app was already running.

- I tried moving it high up in main(), well before my "Geolocator foreground service connected" print, and no change when starting app fresh in debug mode.

- AFTER the app has started, there is no hanging on hot reload.

- Did a clean and rebuild, then ran in debug mode again, same hanging result.
It always hangs on  when my debug prints "Requesting location permission".

**Comment by medyas** [comment]
Getting the same issue @ufukhawk .
Using
Flutter 3.27.1 • channel stable 
```yaml
safe_device: ^1.1.9
geolocator: ^13.0.2
```


Here is the stacktrace :

```shell
          main (timed waiting):tid=1 systid=5791 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:717)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1074)
       at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
       at com.google.android.gms.internal.location.zzau.getLastLocation(com.google.android.gms:play-services-location@@21.0.1:12)
       at com.xamdesign.safe_device.MockLocation.LocationAssistant.checkInitialLocation(LocationAssistant.java:478)
       at com.xamdesign.safe_device.MockLocation.LocationAssistant.access$600(LocationAssistant.java:41)
       at com.xamdesign.safe_device.MockLocation.LocationAssistant$8.onResult(LocationAssistant.java:714)
       at com.xamdesign.safe_device.MockLocation.LocationAssistant$8.onResult(LocationAssistant.java:706)
       at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage(com.google.android.gms:play-services-base@@18.4.0:6)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8249)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
        
```

As you can see in the logs, the main issue is in `checkInitialLocation` https://github.com/ufukhawk/safe_device/blob/6b2274b99038cc00dc3eae64e9b5f780c982f11d/android/src/main/java/com/xamdesign/safe_device/MockLocation/LocationAssistant.java#L477C12-L480C40

**Comment by shahbazhashmi** [comment]
Facing same issue. It's been 2 months still this issue is open. I think I have to find an alternative for this.

**Comment by ufukhawk** [comment]
hi @all 

https://pub.dev/packages/safe_device safe_device: ^1.2.0

pls give feedback this version.

**Comment by RocketeerFly** [comment]
@ufukhawk I can confirm v1.2.0 has resolved the issue on my end
